minimum_pre_commit_version: "4.5.1"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: python
        types: [python]
        additional_dependencies:
          - ruff==0.15.19

      - id: ruff-format
        name: ruff format
        entry: ruff format --check
        language: python
        types: [python]
        additional_dependencies:
          - ruff==0.15.19
